services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                - '%env(REDIS_HOST)%'
                - '%env(int:REDIS_PORT)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'