services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\Security\Jwt\Util\:
        resource: '../../src/Application/Security/Jwt/Util'

    App\Application\Security\Jwt\Util\JwtUtil:
        arguments:
            $jwtAlgorithm: "%jwt_algorithm%"
            $jwtPrivateKey: "%jwt_private_key%"
            $jwtPublicKey: "%jwt_public_key%"