services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Domain\Model\Gallery\Projection\GalleryProjector:
        class: App\Infrastructure\Projection\Gallery\DoctrineGalleryProjector
        arguments: ['@doctrine.dbal.default_connection']

    App\Application\Gallery\Query\AssetQuery:
        class: App\Infrastructure\Query\Gallery\DoctrineAssetQuery
        arguments: ['@doctrine']

    App\Application\Gallery\Query\GalleryQuery:
        class: App\Infrastructure\Query\Gallery\DoctrineGalleryQuery
        arguments: ['@doctrine']

    App\Application\Gallery\Query\V1\ListAllAssetByGalleryHandler:
        class: App\Application\Gallery\Query\V1\ListAllAssetByGalleryHandler
        arguments: ['@App\Application\Gallery\Query\AssetQuery']

    App\Application\Gallery\Query\V1\FindOneGalleryByNameHandler:
        class: App\Application\Gallery\Query\V1\FindOneGalleryByNameHandler
        arguments: ['@App\Application\Gallery\Query\GalleryQuery']

    App\Application\Gallery\Query\V1\FindOneGalleryByUuidHandler:
        class: App\Application\Gallery\Query\V1\FindOneGalleryByUuidHandler
        arguments: ['@App\Application\Gallery\Query\GalleryQuery']

    App\Application\Gallery\Query\V1\ListAllGalleryBySourceHandler:
        class: App\Application\Gallery\Query\V1\ListAllGalleryBySourceHandler
        arguments: ['@App\Application\Gallery\Query\GalleryQuery']

    App\Infrastructure\Persist\Gallery\GalleryRepository:
        class: App\Infrastructure\Persist\Gallery\GalleryRepository
        arguments: ['@messaging.event_storage', '@messaging.snapshot_storage']

    App\Application\Gallery\Command\CreateGalleryHandler:
        class: App\Application\Gallery\Command\CreateGalleryHandler
        arguments: ['@App\Infrastructure\Persist\Gallery\GalleryRepository']

    App\Application\Gallery\Service\GalleryQueryManager:
        class: App\Application\Gallery\Service\GalleryQueryManager
        arguments: ['@messaging.query_bus']

    App\Application\Gallery\Service\GalleryCommandManager:
        class: App\Application\Gallery\Service\GalleryCommandManager
        arguments: ['@messaging.command_bus']

    App\Application\Gallery\Seek\AssetSearcher:
        class: App\Application\Gallery\Seek\AssetSearcher
        arguments: ['@messaging.query_bus']

    App\Application\Gallery\Seek\GallerySearcher:
        class: App\Application\Gallery\Seek\GallerySearcher
        arguments: ['@messaging.query_bus']