imports:
    - { resource: services/* }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Migrations,Tests,Kernel.php}'

    App\Infrastructure\PasswordHasher\PasswordHasherInterface: '@App\Infrastructure\PasswordHasher\Sha1Hasher'
    App\Infrastructure\IdentityGenerator\IdentityGeneratorInterface: '@App\Infrastructure\IdentityGenerator\Uuid4Generator'
